### PR TITLE
More reliable last_cap check

### LINKED ISSUE #22: Improve last cap detection
Hi! I'm developing some changes in util-linux ( https://github.com/karelzak/util-linux/pull/1187 ) for how they detect the last cap from the kernel, and I would like to know if you'd accept a PR to add the same changes here.

Also, do you think a `capng_get_last_cap` call could be added to the API?

### PR DESCRIPTION
**Pull request by ericonr**
Closes #22

### CODE REVIEW

**Comment by stevegrubb** [comment]
Interesting approach. A couple of observations. The capabilities are an array 32 bit unsigned integers where the array size is dictated by VFS_CAP_U32 which currently is 2. That means we have 64 bits right now. So, wouldn't you initialize last_cap  to VFS_CAP_U32 * sizeof(__le32) * 8 rather than INT_MAX? So, you start at 64 its bad, now 32 its good, now 48 its bad, now 40 its good, now 44 its bad, now 42 its bad, now 41 its bad. 40 it is. 

Also, prctl doesn't really need to be in its own function or maybe it should be inlined to avoid overhead?

**Comment by ericonr** [comment]
> The capabilities are an array 32 bit unsigned integers where the array size is dictated by VFS_CAP_U32 which currently is 2. 

That would mean `libcap-ng` has to be recompiled if this value changes?

**Comment by ericonr** [comment]
Updated

**Comment by stevegrubb** [comment]
Yes, if VFS_CAP_U32 changes value, it would require recompiling because all the internal storage is wrong. We'll handle that when that day comes. Thanks for the patch!

**Pull request merged**
