### PR TITLE
fix: README file not found

### PR DESCRIPTION
**Pull request by konosubakonoakua**
introduced by #46

### CODE REVIEW

**Comment by kbowling-bullish** [comment]
> Hmm. If I clone this repo, run ./autogen.sh, then ./configure, then make distcheck, it creates a distributable tarball. If I untar that file, I see the README.md in the directory that was untarred. It seems to be working as expected.

Possibly could be because you have it listed in EXTRA_DIST and it shouldn't be? 
 https://www.gnu.org/software/automake/manual/html_node/Basics-of-Distribution.html seems to indicate (a new enough?) automake will automatically pick up README.md as the README.

**Comment by stevegrubb** [comment]
@kbowling-bullish it still doesn't explain the original problem. It is there if you use autotools correctly. You have to use "make dist" to create the distribution tar file even if it would pick it up automagically. I really don't see a problem here to solve.

**Comment by kbowling-bullish** [comment]
> @kbowling-bullish it still doesn't explain the original problem. It is there if you use autotools correctly. You have to use "make dist" to create the distribution tar file even if it would pick it up automagically. I really don't see a problem here to solve.

It's just results in a build time warning as-is.  Looks like they added the md extension here https://github.com/autotools-mirror/automake/blob/4e6eff3597649782def55fc1dfeeec92cec4b15e/NEWS#L178

**Comment by stevegrubb** [comment]
Thanks for reporting the issue, but I don't think this needs fixing.

**Pull request closed without merging**
