### PR TITLE
Check for prctl options at runtime

### LINKED ISSUE #28: Detect kernel support of PR_CAP_AMBIENT at runtime
The issue I'm facing is that I have containers build with 5.x kernel headers, and the kernel versions I need to support for actual deployment is ranging between 4.1 - 5.x, which is a mix of kernels that may and may not support PR_CAP_AMBIENT.

Building the support of PR_CAP_AMBIENT then run libcap-ng on kernel without actual support would fail almost every function. Build different versions of containers with different kernel headers is not ideal.

If we can detect the support of PR_CAP_AMBIENT at runtime instead of compile time then we can conditionally run code related to PR_CAP_AMBIENT, thus a single build of libcap-ng using new kernel headers can run on both old and new kernel without causing problem.

I'm not really a C programmer, but I imagine we can do something like this:

``` c
#ifdef PR_CAPBSET_DROP
int has_capbset_drop = 1;
rc = prctl(PR_CAPBSET_READ, 0, 0, 0, 0);
if (rc < 0 && errno == EINVAL) { // EINVAL -> kernel does not support PR_CAPBSET_DROP
  has_capbset_drop = 0;
}
if (has_capbset_drop) {
  ...
}
#endif

#ifdef PR_CAP_AMBIENT
int has_ambient = 1;
rc = prctl(PR_CAP_AMBIENT, PR_CAP_AMBIENT_IS_SET, 0, 0, 0);
if (rc < 0 && errno == EINVAL) { // EINVAL -> kernel does not support PR_CAP_AMBIENT
  has_ambient = 0;
}
if (has_ambient) {
  ...
}
#endif
```

I'd happy to make a PR, but I want to hear some thoughts before I proceed.

### PR DESCRIPTION
**Pull request by ntkme**
This PR checks for actual support for prctl option for the running kernel on top of `#ifdef`. This allows libcap-ng compiled with newer version of kernel headers to run in old kernel, which could happen a lot in container world. 

Fixes #28

### CODE REVIEW

**Comment by ntkme** [comment]
I know that the first question people would ask is why don't just upgrade kernel. My answer is that this is for the consideration of containers.

Developers can build the container with new kernel headers, and users may run it in old kernel and libcap-ng would just error out most of the time. If a developer build a container with old kernel headers, and users run it with new kernel, libcap-ng will only do partial work, which would be extremely dangerous. So the only safe way seems to be building container with new kernel headers, and make libcap-ng backward compatible by using run time checks.

Containers has been out there for years and I'm surprised that this issue has never came up. I think it is important to establish this pattern of backward compatibility at runtime. It's not just for supporting old kernels, but also for supporting possible new features in the future kernel versions and making transition between kernel versions more smoothly.

**Comment by stevegrubb** [comment]
@ntkme I still plan to review your patch. I'm busy with some other projects at the moment.

**Comment by stevegrubb** [comment]
I finally had time to review the patch for inclusion. I think that the main thing I need to fix is the detection logic. It is initialized with a 1 and then if the prctl returns EINVAL, then it's set to 0. If the prctl option is not defined because the kernel doesn't support it, then it can never be set to 0 because the test is compiled out by the ifdef. To fix this, we need to reverse the logic. We must assume it does not exist and set the detection to 0, and then prove it exists and set it to 1. The only other issue I see is that I'd prefer the variables to be static rather than hidden.

I'll create a patch to apply on top of this one to fix the issues and then merge it.

**Comment by stevegrubb** [comment]
The patch has been applied. Thanks for your patience. Libcap-ng is not a fast moving project since capabilities don't change very fast.

**Pull request closed without merging**
